/**
 * LLM output section: summary text, matching/conflicts/missing cards
 */

import type { ComparisonResponse, ComparisonRow } from "../types";
import { useEffect, useMemo, useState } from "react";

interface ComparisonSummaryProps {
  result: ComparisonResponse | null;
  error: string | null;
  isLoading: boolean;
  okItems: ComparisonRow[];
  differentItems: ComparisonRow[];
  missingItems: ComparisonRow[];
}

export function ComparisonSummary({
  result,
  error,
  isLoading,
  okItems,
  differentItems,
  missingItems,
}: ComparisonSummaryProps) {
  const summaryText =
    result && typeof result.Summary === "string" ? result.Summary : "";
  const [elapsedSec, setElapsedSec] = useState(0);
  const loadingStages = useMemo(
    () => [
      "Extracting text from both PDFs",
      "Normalizing technical parameters",
      "Comparing values and compatibility states",
      "Building final structured summary",
    ],
    [],
  );

  useEffect(() => {
    if (!isLoading) {
      setElapsedSec(0);
      return;
    }
    const id = window.setInterval(() => setElapsedSec((s) => s + 1), 1000);
    return () => window.clearInterval(id);
  }, [isLoading]);

  const stageIndex = Math.min(
    loadingStages.length - 1,
    Math.floor(elapsedSec / 3),
  );
  const typedDots = ".".repeat((elapsedSec % 3) + 1);

  return (
    <section className="rounded-3xl border border-slate-200/70 bg-white/80 p-6 shadow-sm">
      <h3 className="text-lg font-semibold tracking-tight text-slate-900">
        LLM Output
      </h3>
      <p className="mt-2 text-sm text-slate-500">
        Structured output generated by the model after comparing both PDFs.
      </p>

      {error && (
        <div className="mt-4 rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">
          {error}
        </div>
      )}

      {!result && !isLoading && !error && (
        <div className="mt-6 rounded-2xl border border-dashed border-slate-200 px-4 py-6 text-center text-sm text-slate-500">
          Upload two PDFs on the left to generate the LLM comparison output.
        </div>
      )}

      {!result && isLoading && (
        <div className="mt-6 rounded-2xl border border-blue-100 bg-blue-50/50 px-4 py-4">
          <p className="text-sm font-medium text-blue-900">
            AI comparison in progress ({elapsedSec}s)
          </p>
          <p className="mt-2 text-sm text-blue-800">
            {loadingStages[stageIndex]}
            {typedDots}
          </p>
          <div className="mt-3 h-2 w-full overflow-hidden rounded-full bg-blue-100">
            <div
              className="h-full rounded-full bg-blue-500 transition-all duration-500"
              style={{ width: `${Math.min(95, 18 + elapsedSec * 4)}%` }}
            />
          </div>
          <p className="mt-2 text-xs text-blue-700">
            Output appears automatically when the model finishes.
          </p>
        </div>
      )}

      {result && (
        <div className="mt-6 grid gap-6">
          {summaryText && (
            <div className="rounded-2xl border border-blue-100 bg-blue-50 px-4 py-4 text-sm text-blue-900">
              {summaryText}
            </div>
          )}

          <div className="grid gap-4 md:grid-cols-3">
            <div className="rounded-2xl border border-emerald-100 bg-emerald-50/60 p-4">
              <p className="text-xs font-semibold uppercase tracking-wide text-emerald-600">
                Matching
              </p>
              <p className="mt-2 text-2xl font-semibold text-emerald-700">
                {okItems.length}
              </p>
              <div className="mt-3 space-y-1 text-xs text-emerald-700">
                {okItems.slice(0, 4).map((row) => (
                  <p key={row.parameter}>{row.parameter}</p>
                ))}
                {okItems.length > 4 && (
                  <p className="text-emerald-600">+{okItems.length - 4} more</p>
                )}
              </div>
            </div>

            <div className="rounded-2xl border border-rose-100 bg-rose-50/60 p-4">
              <p className="text-xs font-semibold uppercase tracking-wide text-rose-600">
                Conflicts
              </p>
              <p className="mt-2 text-2xl font-semibold text-rose-700">
                {differentItems.length}
              </p>
              <div className="mt-3 space-y-1 text-xs text-rose-700">
                {differentItems.slice(0, 4).map((row) => (
                  <p key={row.parameter}>{row.parameter}</p>
                ))}
                {differentItems.length > 4 && (
                  <p className="text-rose-600">
                    +{differentItems.length - 4} more
                  </p>
                )}
              </div>
            </div>

            <div className="rounded-2xl border border-amber-100 bg-amber-50/60 p-4">
              <p className="text-xs font-semibold uppercase tracking-wide text-amber-600">
                Missing
              </p>
              <p className="mt-2 text-2xl font-semibold text-amber-700">
                {missingItems.length}
              </p>
              <div className="mt-3 space-y-1 text-xs text-amber-700">
                {missingItems.slice(0, 4).map((row) => (
                  <p key={row.parameter}>{row.parameter}</p>
                ))}
                {missingItems.length > 4 && (
                  <p className="text-amber-600">
                    +{missingItems.length - 4} more
                  </p>
                )}
              </div>
            </div>
          </div>

          {result.raw && (
            <details className="rounded-2xl border border-slate-200 bg-white p-4 text-sm text-slate-600">
              <summary className="cursor-pointer font-semibold text-slate-700">
                Raw model output
              </summary>
              <pre className="mt-3 whitespace-pre-wrap text-xs text-slate-600">
                {String(result.raw)}
              </pre>
            </details>
          )}
        </div>
      )}
    </section>
  );
}
